# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartIQDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ChartIQ', :git => 'https://github.com/ChartIQ/Charting-Library---iOS-SDK.git', :tag => '1.0.1'

  # Pods for ChartIQDemo

  target 'ChartIQDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChartIQDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
